sudo: false
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DEPS=release
  - DEPS=devel
install:
  - pip install -U pip setuptools
  - '[[ "$DEPS" == "devel" ]] && pip install git+https://github.com/pallets/flask.git git+https://github.com/pallets/werkzeug.git || :'
  - pip install -U pytest pytest-cov pytest-mock coveralls flake8
  - pip install -e .[ldap,authlib,sqlalchemy]
script:
  - pytest
  - flake8
after_success:
  - coveralls
notifications:
  email: false
